# Generated by Django 2.0.3 on 2018-03-26 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('captioner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('caption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captioner.Caption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.SmallIntegerField(help_text='How non-glam is this photo? 10 = very normal, 0 = glamourous'),
        ),
    ]
