# Generated by Django 2.0.3 on 2018-03-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captioner', '0002_auto_20180326_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
