# Generated by Django 2.0.3 on 2018-03-26 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('captioner', '0003_auto_20180326_0817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('caption', 'user')},
        ),
    ]
